### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by tlf30** [tlf30/monkey-netty#24]
Opening issue to track the release process for v0.1.0

Version: v0.1.0
Git Tag: v0.1.0
Release champion: @tlf30, Trevor Flynn, trevorflynn@liquidcrystalstudios.com

Pre-release checklist

- [x] All issues and merge/pull requests for release are closed or merged
- [x] Change long is updated (#25)
- [x] All license info is updated (#21, #23)
- [x] Version number and build script changes are complete (#24)

Post-release checklist

- [x] CI pipeline succeeded
- [x] Git tag created
- [x] GitHub release created
- [x] Packages available  
- [x] Close GitHub release project
- [x] Update jMonkeyStore page (changes done, pending submittion)
- [x] Create release post on jMonkeyEngine Hub

This issue may be closed when release is complete.

**Comment by tlf30** [comment]
@oxplay2 in preparation for the release, I have created a wiki: https://github.com/tlf30/monkey-netty/wiki
When you get time, can you please look it over and let me know what you think. Also, I have updated the readme in PR #25 for the release, when you get a sec, let me know what you think.

**Comment by oxplay2** [comment]
wow, this wiki is really nice! 

nothing more to add, its just well done.

**Comment by tlf30** [comment]
Got a 422 on CI pipeline for publishing, currently investigating.

**Comment by tlf30** [comment]
Simply re-running it seemed to fix it.

**Comment by tlf30** [comment]
Release complete!
